ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from order import views as OrderViews
from user import views as UserViews
from home import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.conf.urls import (handler400, handler403, handler404, handler500)
handler400 = 'home.views.bad_request'
handler403 = 'home.views.permission_denied'
handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

urlpatterns = [
    path('boss/', admin.site.urls),
    path('', include('home.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('contact/', views.contactus, name='contactus'),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),

    path('activate/<uidb64>/<token>/', UserViews.activate_account, name='activate'),
    
    path('sitemap/', views.sitemap, name='sitemap'),



    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),      


    
    #path('search/', views.search, name='search'),
    ##path('search_auto/', views.search_auto, name='search_auto'),
    ##path('faq/', views.faq, name='faq'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('addfile', views.addfile, name='addfile'),
    ]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.http import request
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    smtpserver = models.CharField(blank=True,max_length=50)
    smtpemail = models.CharField(blank=True,max_length=50)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    youtube = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name= models.CharField(blank=True,max_length=20)
    email= models.CharField(blank=True,max_length=50)
    subject= models.CharField(blank=True,max_length=50)
    message= models.TextField(blank=True,max_length=255)
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject','message']
        widgets = {
            'name'   : TextInput(attrs={'class': 'input','placeholder':'Name & Surname', 'required': True}),
            'subject' : TextInput(attrs={'class': 'input','placeholder':'Subject', 'required': True}),
            'email'   : TextInput(attrs={'class': 'input','placeholder':'Email Address', 'required': True}),
            'message' : Textarea(attrs={'class': 'input','placeholder':'Your Message','rows':'5', 'required': True}),
        }


""" class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=200)
    answer = RichTextUploadingField()
    status=models.CharField(max_length=10, choices=STATUS)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question """

order/models.py
#pylint: disable = E1101
#pylint: disable = W0614

from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.core.validators import MinValueValidator, MaxValueValidator
from home.validators import validate_file_size
from django.http import HttpResponse

########## File system #########


class FOrder(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=6, editable=False)
    first_name = models.CharField(max_length=30, blank=False)
    phone = models.EmailField(max_length=25, blank=False)
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    files = models.FileField(upload_to='images/', blank=False, validators=[validate_file_size])
    reports = models.FileField(upload_to='images/', blank=True, validators=[validate_file_size])

    def __str__(self):
        return str(self.id)
    
    @property
    def reports_url(self):
        if self.reports and hasattr(self.reports, 'url'):
            return self.reports.url
        else:
            return "Not Ready"

class FOrderForm(ModelForm):
    class Meta:
        model = FOrder
        fields = ['first_name', 'phone', 'files']



######## End Filesystem #########




# class Order(models.Model):
#     STATUS = (
#         ('New', 'New'),
#         ('Accepted', 'Accepted'),
#         ('Preaparing', 'Preaparing'),
#         ('OnShipping', 'OnShipping'),
#         ('Completed', 'Completed'),
#         ('Canceled', 'Canceled'),
#     )
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
#     code = models.CharField(max_length=6, editable=False)
#     first_name = models.CharField(max_length=30, blank=True)
#     last_name = models.CharField(max_length=10, blank=True)
#     phone = models.CharField(blank=True, max_length=15)
#     phone_company = models.CharField(blank=True, max_length=20)
#     phone_location = models.CharField(blank=True, max_length=20)

#     address = models.CharField(blank=True, max_length=150)
#     city = models.CharField(blank=True, max_length=30)
#     country = models.CharField(blank=True, max_length=20)
#     account = models.CharField(blank=True, max_length=30)
#     total = models.FloatField()
#     status = models.CharField(max_length=20, choices=STATUS, default='New')
#     ip = models.CharField(blank=True, max_length=20)
#     adminnote = models.CharField(blank=True, max_length=100)
#     create_at = models.DateTimeField(auto_now_add=True)
#     update_at = models.DateTimeField(auto_now=True)
#     files = models.FileField(upload_to='images/', blank=True, default='images/placeholder.png', validators=[validate_file_size])


#     def __str__(self):
#         return str(self.id)


# class OrderForm(ModelForm):
#     class Meta:
#         model = Order
#         fields = ['first_name', 'last_name',
#                   'address', 'phone', 'city', 'country', 'account', 'files']

user/models.py
#pylint: disable=E1101
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.forms import ModelForm
from order.models import FOrder
from django.db.models.signals import post_save
from django.dispatch import receiver
from home.validators import validate_file_size

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=50)
    country = models.CharField(blank=True, max_length=50)
    image = models.ImageField(blank=True, upload_to='images/users/')
    email_confirmed = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username       
           
    def username(self):
        return self.user.username

    def email(self):
        return self.user.email

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class Reply(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    order = models.ForeignKey(FOrder, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    reply = models.CharField(max_length=250, blank=True)
    ip = models.CharField(max_length=20, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to='images/', blank=True, default='images/placeholder.png', validators=[validate_file_size])

    def __str__(self):
        return self.subject
    
    def image_tag(self):
        if self.image is not None:
            return mark_safe('<img src="/uploads/%s" height="40" width="100">' % (self.image))
        else:
            return 'images/placeholder.png'

    image_tag.short_description = 'Image'

class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['subject', 'reply', 'image']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput
from.models import UserProfile



class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(required=True)

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("Email is already registered")
        return self.cleaned_data['email']

    first_name = forms.CharField(
        max_length=50, label='First Name :')
    last_name = forms.CharField(
        max_length=50, label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2', )


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'country', 'city', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'city': TextInput(attrs={'class': 'input', 'placeholder': 'city'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }

order/views.py
#pylint: disable = E1101
#pylint: disable = W0614

from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage, BadHeaderError
from django.core.exceptions import ValidationError

from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from order.models import FOrderForm, FOrder
from user.models import*
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from django.template import loader
from django.template.loader import render_to_string
from django.db.models.signals import post_save
from django.db.models import F
from home.models import Setting
import messagebird
import requests

######## File system  #########

@login_required(login_url='/login')
def addfile(request):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user
    if request.method == 'POST':  # if there is a post
        form = FOrderForm(request.POST, request.FILES)
        if form.is_valid():
            data = FOrder()
            data.first_name = form.cleaned_data['first_name']
            data.phone = form.cleaned_data['phone']
            data.files = form.cleaned_data['files']
            data.user_id = current_user.id
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(6).upper()  # random cod
            data.code = ordercode
            data.save()
            messages.success(request, 'Your file has ben sent. Please follow your dashboard for report')
            return redirect('/user')
        else:
            messages.warning(request, 'The maximum file size that can be uploaded is 2MB')      
            return HttpResponseRedirect(url)
    return render(request, 'F_Form.html')

order/templates/F_Form.html
{% extends 'homebase.html' %}
{% block title %} Shop Cart {% endblock %}
{% block description %} {% endblock %}
{% block keywords %} {% endblock %}
{% load static %}


{% block body %}

<div class="row justify-content-center" style="padding:10%">


    <div class="col-lg-7" style="margin-top: 0;">
        <div class="box-element">

            <a class="get-started-btn" style="border-radius: 4px; border: none;" href="/user">Dashboard</a>

            <br>
            <br>


        </div>

        <br>
        <div class="box-element"">
            <Form id=" form" onsubmit="return validateForm()" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="billing-details">

                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" name="first_name" class="form-control input"
                            maxlength="15" id="id_first_name" placeholder="Title..." required>
                    </div>

                </div>


                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">E-mail</label>
                    <div class="col-sm-10">
                        <input type="email" name="phone" class="form-control input"
                            maxlength="30" id="id_phone" placeholder="E-mail..." required>
                    </div>

                </div>

                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">File</label>
                    <div class="col-sm-10">
                    <input id="id_file" type="file" class="" name="files" required>
                    </div>
                </div>

            </div>

            <hr>
            <input id="form-button" class="btn btn-success btn-block"
            style=" border: none; border-radius: 4px; background: #37517e; color:white;font-weight:600; text-align: center; padding:5px;"
            type="submit" value="Upload your file" />

            </Form>

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock body %}

order/templates/Order_Completed.html
{% extends 'homebase.html' %}

{% block title %}This is home{% endblock %}
{% block keywords %}This is home keywords{% endblock %}
{% block description %}This is home description{% endblock %}

{% block sidebar %} {% endblock %}
{% block slider %} {% endblock %}
{% block body %} 

{% load static %}

<!-- BREADCRUMB -->
<div id="breadcrumb" style="padding-top: 10%;">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li class="active">Order Complated</li>
        </ul>
    </div>
</div>
{% if ordercode == None %}
<div class="box-element product col-lg-6" style="padding-left:20%; display:flexbox;">
    <a class="btn btn-outline-dark" href="/">&#x2190; Continue Shopping</a>
    <br>
    <br>
    <p>
    <h2>No item in cart</h2>
    </p>
</div>

{% else %}
<!-- /BREADCRUMB -->
<!-- section -->
<div class="section">

    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Order Complated</h3>
                    </div>
                    <hr>
                    <h2>Dear {{ user.first_name }} {{  user.last_name }}</h2>
                    <hr>
                    <h3>Your order is completed</h3>
                    <h3>Order Code : {{ ordercode }}</h3>
                    <h3> Phone : {{ profile.phone }}</h3>
                    <h3>Email : {{ order.address }}</h3>
                    <h3>Thank You</h3>
                     {{ user.first_name }}
                        <hr> {{ user }}
                        <hr> {{ user.email }}
                    <hr>

                </div>

            </div>


        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->
{% endif %}

{% endblock %}

{% block content %}
<div class="pull-left">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{ message | safe }}
    </div>
    {% endfor %}
    {% endif %}
</div>		
{% endblock content %}

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% block title %} Shop Cart {% endblock %}
{% block description %} {% endblock %}
{% block keywords %} {% endblock %}
{% load static %}


{% block body %}

<section>
    <div class="row justify-content-center" style="padding:5%">

        {% if total == 0  %}

        <div class="box-element product col-lg-6" style="padding-left:20%; display:flexbox;">
            <div class="pull-left">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{ message | safe }}
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <a class="btn btn-outline-dark" href="/">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <p>
            <h2>No item in cart</h2>
            </p>
        </div>

        {% else %}
        <div class="col-lg-5">

            <div class="pull-left">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{ message | safe }}
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <div class="box-element"">
            <Form id=" form" onsubmit="return validateForm()" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="billing-details">

                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">First Name</label>
                        <div class="col-sm-10">
                            <input type="text" name="first_name" value="{{ user.first_name }}"
                                class="form-control input" maxlength="15" id="id_first_name"
                                placeholder="First Name...">
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">Last Name</label>
                        <div class="col-sm-10">
                            <input type="text" name="last_name" class="form-control input" maxlength="15"
                                id="id_last_name" placeholder="Last Name...">
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">Phone</label>
                        <div class="col-sm-10">
                            <input type="text" name="phone" value="{{ user.phone }}" class="form-control input"
                                maxlength="15" id="id_phone" placeholder="Phone...">
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" name="address" value="{{ user.first_name }}" class="form-control input"
                                maxlength="20" id="id_address" placeholder="Email...">
                        </div>

                    </div>
                    <hr>
                    <p>Optional Information:</p>
                    <hr>
                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">City</label>
                        <div class="col-sm-10">
                            <input type="text" name="city" class="form-control input" maxlength="15" id="id_city"
                                placeholder="City...">
                        </div>

                    </div>
                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">Country</label>
                        <div class="col-sm-10">
                            <input type="text" name="country" class="form-control input" maxlength="15" id="id_country"
                                placeholder="Country...">
                        </div>

                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-2 col-form-label">Account</label>
                        <div class="col-sm-10">
                            <input type="text" name="account" class="form-control input" maxlength="30" id="id_account"
                                placeholder="Account...">
                        </div>

                    </div>

                    <div class="form-group">
                        <input id="id_file" type="file" class="" name="files">
                    </div>

                    <div class="form-group row">

                        <input type="password" class="form-control" id="pwd">
                        <label for="pwd">Password</label>
                    </div>



                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Place Order">

                </Form>

                <script type="text/javascript">
                    var total = '{{total}}'

                    function validateForm() {
                        var total = '{{total}}'
                        if (total == 0) {
                            alert("You dont have any item in cart");
                            return false;
                        }
                        else alert('Transaction complited');
                    }
                </script>


            </div>


        </div>

        <div class="col-lg-7" style="margin-top: 0;">

            <div class="box-element">

                <a class="btn btn-outline-dark" href="/">&#x2190; Continue Shopping</a>

                <br>
                <br>


            </div>

            <br>
            <div class="box-element">
                <div class="cart-row" style="padding-left: 0;">
                    <div style="flex:1"></div>
                    <div style="flex:1"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1; padding-left: -20px;"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for rs in shopcart %}
                <div class="cart-row">

                    <div style="flex:1;">
                        {% if rs.variant.image_id  > 0 %}
                        <img class="row-image" src="{{rs.variant.image}}" alt="" style="height: 5vh; width: auto;">
                        {% else %}
                        <img class="row-image" src="{{rs.product.image.url}}" style="height: 5vh; width: auto;">
                        {% endif %}
                    </div>

                    <div style="flex:1">
                        <p style="padding-right: 10px;">{{ rs.variant.size }} to {{ rs.variant.color }}</p>
                    </div>
                    <div style="flex:1">
                        <p style="padding-left: 20px;">
                            {% if rs.product.variant == 'None' %}
                            {{ rs.product.price|floatformat:2 }}
                            {% else %}
                            {{ rs.variant.price|floatformat:2 }}
                            {% endif %}
                        </p>
                    </div>
                    <div style="flex:1">
                        <p style="padding-left: 20px;"> {{rs.quantity}}</p>
                    </div>
                    <div style="flex:1">
                        <p style="padding-left: 20px;">$
                            {% if rs.product.variant == 'None' %}
                            {{ rs.amount|floatformat:2 }}
                            {% else %}
                            {{ rs.varamount|floatformat:2 }}
                            {% endif %}</p>
                    </div>
                    <div style="flex:1 text-left">
                        <p><a href="/order/deletefromcart/{{ rs.id }}"
                                onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn">
                                <iclass="fa fa-close">x</i>
                            </a>
                        </p>
                    </div>
                </div>
                {% endfor %}
                <table class="text-right" style="float:right">
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL ITEMS</th>
                        <th colspan="2" class="sub-total">{{ subtotal}}</th>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>PROCESSING FEE</th>
                        <td colspan="2">FREE</td>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">${{ total}}</th>
                    </tr>
                </table>

                <table class="table">

                    <tr>
                        <th>
                            <h5>Items: <strong>{{ subtotal}}</strong></h5>
                        </th>
                        <th>
                            <h5>Total:<strong> ${{total|floatformat:2}}</strong></h5>
                        </th>
                    </tr>
                </table>
                <hr>

            </div>

        </div>
        {% endif %}



    </div>
</section>
<style>
    form {
        margin: 30px;
    }

    .form-group {
        position: relative;
    }

    label {
        position: absolute;
        left: 10px;
        top: 10px;
        transition: all 0.3s;
        color: #999;
        font-weight: normal;
    }

    .form-control:focus~label {
        left: 5px;
        top: -10px;
        background: #fff;
        padding: 0 5px;
    }

    label.active {
        left: 5px;
        top: -10px;
        background: #fff;
        padding: 0 5px;
    }


    /* Change Autocomplete styles in Chrome*/
    input:-webkit-autofill,
    input:-webkit-autofill:hover,
    input:-webkit-autofill:focus,
    textarea:-webkit-autofill,
    input:-webkit-autofill:active,
    textarea:-webkit-autofill:hover,
    textarea:-webkit-autofill:focus,
    select:-webkit-autofill,
    select:-webkit-autofill:hover,
    select:-webkit-autofill:focus {
        /* border: 1px solid green; */
        /* -webkit-text-fill-color: green !important; */
        -webkit-text-fill-color: black;
        transition: background-color 5000s ease-in-out 0s;
    }
</style>

<script>
    $(document).ready(function () {

        $(".form-group .form-control").blur(function () {
            if ($(this).val() != "") {
                $(this).siblings("label").addClass("active");
            } else {
                $(this).siblings("label").removeClass("active");
            }
        });
    });
</script>


{% endblock body %}

order/templates/femail.html
<h1>This is files test email</h1>